### ISSUE TITLE
Spelling fixes

### ISSUE THREAD

**Issue by skirpichev** [artlebedev/parser3#1]
https://salsa.debian.org/sk-guest/parser/-/blob/master/debian/patches/108_spelling.patch

**Comment by moko-als** [comment]
https://github.com/artlebedev/parser3/commit/1217157b3f6f6d6cc724c1b62554cc6f0388c674 - It was applied 3 years ago...

**Comment by skirpichev** [comment]
Hmm, sorry, it seems so.  Maybe it's time for the new release)

**Comment by moko-als** [comment]
Right after we stabilize the code for the embedded http server. :)
https://github.com/artlebedev/parser3/commit/4178b1a3976533dea65b6899b7223b8396232c54
