### ISSUE TITLE
incompatible with libxml2-2.9.11

### ISSUE THREAD

**Issue by Anubioz** [artlebedev/parser3#2]
Libxml2 added checking for invalid XML redeclarations [in this commit](https://github.com/GNOME/libxml2/commit/01411e7c5ea0fff181271e092f46a2138c3720ec) and that is exactly what parser3 does, so when used on a system where libxml2>=2.9.11 it fails with the following error:

 xmlAddEntity: invalid redeclaration of predefined entityxmlAddEntity: invalid redeclaration of predefined entity

**Comment by moko-als** [comment]
Please tell how to reproduce the issue. Just compiled with buildall using libxml2-2.9.12 (it requires --without-python option to build libxslt and old xml2-config as they broke compatibility with libxslt-1.1.34 checks in its Configure). All tests passed. If you have &lt;!ENTITY lt "&lt;"&gt;  in your symbols.ent and it stopped working - it's not parser3 issue...
